-- =====================================================================
--  TerraFront — corriger les 140 communes dont le gentile est celui
--  d'une commune absorbee
--
--  Ces codes INSEE portent DEUX articles sur Wikipedia : celui de la
--  commune actuelle et celui d'une commune qu'elle a absorbee. Le
--  premier import a pris le premier venu, si bien que Surjoux-Lhopital
--  a recu « Hospitaliers », le nom des habitants de Lhopital.
--
--  Seul le nom de ta commune permet de trancher, et il est en base :
--  c'est donc la requete qui choisit, pas le fichier. Les deux candidats
--  sont ecrits ci-dessous, la base garde celui dont le titre d'article
--  correspond au nom de la commune.
--
--  Les accents ne concordent pas toujours entre l'INSEE et Wikipedia —
--  « Surjoux-Lhopital » contre « Surjoux-Lhopital » — d'ou unaccent.
--
--  Rien a reimporter. Colle tout et lance. Idempotent.
-- =====================================================================

create extension if not exists unaccent;

with candidats(code, titre, gentile) as (values
  ('01033', 'Bellegarde-sur-Valserine', 'Bellegardiens · Bellegardiennes'),
  ('01033', 'Valserhône', 'Valserhônois · Valserhônoises'),
  ('01215', 'Lhôpital', 'Hospitaliers'),
  ('01215', 'Surjoux-Lhopital', 'Surdiolans · Surdiolanes'),
  ('01450', 'Villieu-Loyes-Mollon', 'Villacuciens · Villacuciennes'),
  ('01450', 'Villieu', 'Villacusiens'),
  ('02439', 'Longueval-Barbonval', 'Longuevallois · Longuevalloises'),
  ('02439', 'Longueval (Aisne)', 'Longuevallois'),
  ('08105', 'Charleville-Mézières', 'Carolomacériens'),
  ('08105', 'Charleville (Ardennes)', 'Carolopolitains'),
  ('09334', 'Vicdessos', 'Vicdessois'),
  ('09334', 'Val-de-Sos', 'Val-de-sossois'),
  ('11304', 'Quillan (ancienne commune)', 'Quillanais · Quillanaises'),
  ('11304', 'Quillan', 'Quillanais'),
  ('12021', 'La Bastide-l''Évêque', 'Épiscopois · Épiscopoises'),
  ('12021', 'Le Bas Ségala', 'Bastidiens'),
  ('12120', 'Laissac', 'Laissaguais'),
  ('12120', 'Laissac-Sévérac l''Église', 'Laissaguais-Sévéragais'),
  ('12270', 'Sévérac-le-Château', 'Sévéragais · Sévéragaises'),
  ('12270', 'Sévérac d''Aveyron', 'Sévéragais'),
  ('14005', 'Airan', 'Airannais'),
  ('14005', 'Valambray', 'Ambrayvalois'),
  ('14061', 'Le Bény-Bocage', 'Bény-Bocains'),
  ('14061', 'Souleuvre en Bocage', 'Souleuvrais'),
  ('14098', 'Bretteville-l''Orgueilleuse', 'Brettevillais · Brettevillaises'),
  ('14098', 'Thue et Mue', 'Thuemusiens'),
  ('14658', 'Saint-Sever-Calvados', 'Séverins'),
  ('14658', 'Noues de Sienne', 'Noues des'),
  ('15108', 'Loubaresse (Cantal)', 'Loubaressois · Loubaressoises'),
  ('15108', 'Val d''Arcomie', 'Val d’Arcomiens · Val d’Arcomiennes'),
  ('15141', 'Neussargues-Moissac', 'Neussarguais · Neussarguaises'),
  ('15141', 'Neussargues en Pinatelle', 'Neussarguais'),
  ('15142', 'Neuvéglise', 'Neuvéglisiens · Neuvéglisiennes'),
  ('15142', 'Neuvéglise-sur-Truyère', 'Neuvéglisiens'),
  ('16186', 'Lignières-Sonneville', 'Lignerois'),
  ('16186', 'Lignières-Ambleville', 'Ligniérois'),
  ('16233', 'Mosnac (Charente)', 'Mosnacais'),
  ('16233', 'Mosnac-Saint-Simeux', 'Simosnacois'),
  ('16339', 'Auge-Saint-Médard', 'Médardais'),
  ('16339', 'Val-d''Auge', 'Valdaugeois'),
  ('17277', 'Saint-Denis-du-Pin', 'Diony-Sapinois'),
  ('17277', 'Essouvert', 'Essouvertois · Essouvertoises'),
  ('17295', 'Réaux', 'Réaulais'),
  ('17295', 'Réaux sur Trèfle', 'Réaulais · Réaulaises'),
  ('19248', 'Saint-Ybard', 'Saint-Ybartois'),
  ('19248', 'Les Trois-Saints', 'Trois-Saintois · Trois-Saintoises'),
  ('19252', 'Sarroux', 'Sarrousiennes'),
  ('19252', 'Sarroux - Saint Julien', 'Sarrousiens'),
  ('22055', 'Binic-Étables-sur-Mer', 'Binicais'),
  ('22055', 'Étables-sur-Mer', 'Tagarins · Tagarines'),
  ('22084', 'Jugon-les-Lacs (commune déléguée)', 'Jugonnais · Jugonnaises'),
  ('22084', 'Jugon-les-Lacs', 'Jugonnais'),
  ('22093', 'Lamballe', 'Lamballais · Lamballaises'),
  ('22093', 'Lamballe (ancienne commune nouvelle)', 'Lamballais · Lamballaises'),
  ('22093', 'Lamballe-Armor', 'Lamballe-Armoricains'),
  ('22183', 'Plémet (commune déléguée)', 'Plémetais · Plémetaises'),
  ('22183', 'Plémet', 'Plémétais'),
  ('22203', 'Plœuc-L''Hermitage', 'Plœucois'),
  ('22203', 'Plœuc-sur-Lié', 'Plœucois · Plœucoises'),
  ('22209', 'Ploubalay', 'Ploubalaysiens'),
  ('22209', 'Beaussais-sur-Mer', 'Beaussaisiens'),
  ('22251', 'Pordic (commune déléguée)', 'Pordicais · Pordicaises'),
  ('22251', 'Pordic', 'Pordicais'),
  ('22264', 'La Roche-Derrien', 'Rochois · Rochoises'),
  ('22264', 'La Roche-Jaudy', 'Rochois'),
  ('24117', 'Les Coteaux Périgourdins', 'Costellois périgourdins'),
  ('24117', 'Chavagnac (Dordogne)', 'Chavagnacois · Chavagnacoises'),
  ('24142', 'Coux-et-Bigaroque', 'Couxois'),
  ('24142', 'Coux et Bigaroque-Mouzens', 'Couzensois'),
  ('25147', 'Chemaudin', 'Chemaudinois'),
  ('25147', 'Chemaudin et Vaux', 'Chemaudinois-Vauliers'),
  ('25390', 'Montbenoît', 'Saugets'),
  ('25390', 'Pays-de-Montbenoît', 'Saugets · Saugettes'),
  ('25434', 'Ornans', 'Ornanais'),
  ('25434', 'Ornans (commune déléguée)', 'Ornanaises'),
  ('27058', 'Les Trois Lacs', 'Troilaciens · Troilaciennes'),
  ('27058', 'Bernières-sur-Seine', 'Berniérois'),
  ('27213', 'Vexin-sur-Epte', 'Eptin véliocasses'),
  ('27213', 'Écos', 'Écosiens'),
  ('27676', 'Venables', 'Venablois'),
  ('27676', 'Les Trois Lacs', 'Troilaciens · Troilaciennes'),
  ('27679', 'Verneuil-sur-Avre', 'Vernoliens'),
  ('27679', 'Verneuil d''Avre et d''Iton', 'Vernoliens · Vernoliennes'),
  ('31277', 'Lasserre (Haute-Garonne)', 'Lasserrois · Lasserroises'),
  ('31277', 'Lasserre-Pradère', 'Lasserro-Pradérois'),
  ('31471', 'Saint-Béat', 'Saint-Béatais'),
  ('31471', 'Saint-Béat-Lez', 'Saint-Béatais-Léziens'),
  ('32079', 'Castelnau d''Auzan Labarrère', 'Auzannais-Labarrerois'),
  ('32079', 'Castelnau-d''Auzan', 'Auzanais · Auzanaises'),
  ('33008', 'Arbis', 'Arbissois'),
  ('33008', 'Porte-de-Benauge', 'Benaugeois'),
  ('33018', 'Aubie-et-Espessas', 'Albins'),
  ('33018', 'Val de Virvée', 'Virvéens'),
  ('33055', 'Blaignan', 'Blaignanais'),
  ('33055', 'Blaignan-Prignac', 'Blaignanais-Prignacais'),
  ('33268', 'Margaux (Gironde)', 'Margalais'),
  ('33268', 'Margaux-Cantenac', 'Margalais-Cantenacais'),
  ('35004', 'Antrain', 'Antrainais · Antrainaises'),
  ('35004', 'Val-Couesnon', 'Valaisiens · Valaisiennes'),
  ('35069', 'Châteaugiron', 'Castelgironnais · Castelgironnaises'),
  ('35069', 'Châteaugiron (commune déléguée)', 'Castelgironnais'),
  ('35176', 'Messac (Ille-et-Vilaine)', 'Messacois'),
  ('35176', 'Guipry-Messac', 'Guissacois · Guissacoises'),
  ('35257', 'Saint-Brice-en-Coglès', 'Briçois'),
  ('35257', 'Maen Roch', 'Maenroquois · Maenroquoises'),
  ('35308', 'Mesnil-Roc''h', 'Mesniliens'),
  ('35308', 'Saint-Pierre-de-Plesguen', 'Saint-Pierrais · Saint-Pierraises'),
  ('38152', 'Eclose-Badinières', 'Agnysiens · Agnysiennes'),
  ('38152', 'Eclose', 'Éclosiens'),
  ('38395', 'Saint-Hilaire (Isère)', 'Saint-Hilairois'),
  ('38395', 'Plateau-des-Petites-Roches', 'Petit-Rochois'),
  ('39510', 'Septmoncel', 'Septmoncelands'),
  ('39510', 'Septmoncel les Molunes', 'Septmoncelands-Molunois'),
  ('41055', 'Chouzy-sur-Cisse', 'Calcissiens'),
  ('41055', 'Valloire-sur-Cisse', 'Valcissiens'),
  ('41142', 'Molineuf', 'Molineuvois'),
  ('41142', 'Valencisse', 'Non définis'),
  ('41151', 'Montrichard', 'Montrichardais'),
  ('41151', 'Montrichard Val de Cher', 'Montrichardais · Montrichardaises'),
  ('41167', 'Onzain', 'Onzainois'),
  ('41167', 'Veuzain-sur-Loire', 'Veuzainois'),
  ('41171', 'Oucques', 'Oucquois'),
  ('41171', 'Oucques La Nouvelle', 'Oucquois · Oucquoises'),
  ('41173', 'Ouzouer-le-Marché', 'Oratoriens'),
  ('41173', 'Beauce la Romaine', 'Belsaromains'),
  ('44003', 'Ancenis', 'Anceniens'),
  ('44003', 'Ancenis-Saint-Géréon', 'Anceniens · Anceniennes'),
  ('44005', 'Chaumes-en-Retz', 'Calmetiens'),
  ('44005', 'Arthon-en-Retz', 'Arthonnais'),
  ('44021', 'Bourgneuf-en-Retz', 'Novembourgeois'),
  ('44021', 'Villeneuve-en-Retz', 'Villeretziens · Villeretziennes'),
  ('44029', 'La Chapelle-Basse-Mer', 'Chapelains'),
  ('44029', 'Divatte-sur-Loire', 'Divattais'),
  ('44163', 'Saint-Herblon', 'Saint-Herblonnais'),
  ('44163', 'Vair-sur-Loire', 'Vairlois'),
  ('44180', 'Saint-Mars-la-Jaille', 'Saint-Marsiens'),
  ('44180', 'Vallons-de-l''Erdre', 'Valonais'),
  ('44213', 'Varades', 'Varadais'),
  ('44213', 'Loireauxence', 'Loireauxençois · Loireauxençoises'),
  ('48009', 'Aumont-Aubrac', 'Aumonais'),
  ('48009', 'Peyre en Aubrac', 'Peyrens'),
  ('48050', 'Cocurès', 'Cocuréléens'),
  ('48050', 'Bédouès-Cocurès', 'Bédouesquins · Bédouesquines'),
  ('48087', 'Malbouzon', 'Malbouzonois'),
  ('48087', 'Prinsuéjols-Malbouzon', 'Prinsuéjoliens · Prinsuéjoliennes'),
  ('48105', 'Naussac (Lozère)', 'Naussacois'),
  ('48105', 'Naussac-Fontanes', 'Naussacois-Fontanais'),
  ('49050', 'Brissac-Quincé', 'Brissacois'),
  ('49050', 'Brissac Loire Aubance', 'Brilaubançais'),
  ('49069', 'Champtoceaux', 'Castrocelsiens'),
  ('49069', 'Orée d''Anjou', 'Oréens · Oréennes'),
  ('49092', 'Chemillé', 'Chemillois'),
  ('49092', 'Chemillé-en-Anjou', 'Chemillois · Chemilloises'),
  ('49126', 'Drain (Maine-et-Loire)', 'Drainois'),
  ('49126', 'Orée d''Anjou', 'Oréens · Oréennes'),
  ('49160', 'Ingrandes (Maine-et-Loire)', 'Ingrandais'),
  ('49160', 'Ingrandes-Le Fresne sur Loire', 'Ingrando-Fresnois'),
  ('49160', 'Ingrandes-le-Fresne-sur-Loire', 'Ingrando-Fresnois'),
  ('49200', 'La Membrolle-sur-Longuenée', 'Membrollais'),
  ('49200', 'Longuenée-en-Anjou', 'Longuenéens'),
  ('49244', 'La Pommeraye (Maine-et-Loire)', 'Pommeréyens'),
  ('49244', 'Mauges-sur-Loire', 'Mauligériens'),
  ('49248', 'Pouancé', 'Pouancéens'),
  ('49248', 'Ombrée d''Anjou', 'Ombréens · Ombréennes'),
  ('49292', 'Saint-Lambert-du-Lattay', 'Saint-Lambertins'),
  ('49292', 'Val-du-Layon', 'Layonvalois'),
  ('49301', 'Sèvremoine', 'Sèvréens'),
  ('49301', 'Saint-Macaire-en-Mauges', 'Macairois'),
  ('49307', 'Saint-Mathurin-sur-Loire', 'Mathurinois'),
  ('49307', 'Loire-Authion', 'Loire-Authiens'),
  ('49323', 'Saint-Sylvain-d''Anjou', 'Saint-Sylvanais'),
  ('49323', 'Verrières-en-Anjou', 'Verrois'),
  ('49367', 'Vern-d''Anjou', 'Vernois'),
  ('49367', 'Erdre-en-Anjou', 'Erdréens'),
  ('50041', 'Beaumont-Hague', 'Beaumontais'),
  ('50041', 'La Hague', 'Haguais'),
  ('50129', 'Cherbourg-Octeville', 'Cherbourgeois-Octevillais'),
  ('50129', 'Cherbourg-en-Cotentin', 'Cherbourgeois'),
  ('50412', 'Portbail', 'Portbaillais'),
  ('50412', 'Port-Bail-sur-Mer', 'Port-Baillais'),
  ('50546', 'Bourgvallées', 'Valléens'),
  ('50546', 'Saint-Samson-de-Bonfossé', 'Samsonnais'),
  ('50601', 'Torigni-sur-Vire', 'Torignais'),
  ('50601', 'Torigny-les-Villes', 'Torivillois'),
  ('50611', 'Urville-Hague', 'Urvillais'),
  ('50611', 'Urville-Nacqueville', 'Urvillo-Nacquevillais'),
  ('53017', 'Ballée', 'Balléens'),
  ('53017', 'Val-du-Maine', 'Valmainois'),
  ('53104', 'Gennes-sur-Glaize', 'Gennois'),
  ('53104', 'Gennes-Longuefuye', 'Longennois'),
  ('53124', 'Laigné', 'Laignéens'),
  ('53124', 'Prée-d''Anjou', 'Préens'),
  ('53136', 'La Roche-Neuville', 'Rocheneuvillois'),
  ('53136', 'Loigné-sur-Mayenne', 'Loignéens'),
  ('53249', 'Saint-Pierre-sur-Orthe', 'Pétruciens'),
  ('53249', 'Vimartin-sur-Orthe', 'Vimartois'),
  ('54099', 'Briey (Meurthe-et-Moselle)', 'Briotins'),
  ('54099', 'Val de Briey', 'Val des'),
  ('56251', 'Theix', 'Theixois'),
  ('56251', 'Theix-Noyalo', 'Theixnoyalais'),
  ('60029', 'Auneuil (commune déléguée)', 'Auneuillois'),
  ('60029', 'Auneuil', 'Auneuillois · Auneuilloises'),
  ('60256', 'Montchevreuil', 'Monchevreuilletais · Monchevreuilletaises'),
  ('60256', 'Fresneaux-Montchevreuil', 'Frenexilliens · Frenexilliennes'),
  ('61292', 'Montsecret', 'Montsecréens'),
  ('61292', 'Montsecret-Clairefougère', 'Clarafilisecrémontins · Clarafilisecrémontines'),
  ('61341', 'Radon (Orne)', 'Radonnais'),
  ('61341', 'Écouves', 'Écouviens · Écouviennes'),
  ('61375', 'Saint-Christophe-le-Jajolet', 'Jajoléens'),
  ('61375', 'Boischampré', 'Boischampréens'),
  ('61484', 'Le Theil (Orne)', 'Theillois'),
  ('61484', 'Val-au-Perche', 'Perchevalois'),
  ('62447', 'Hesdin', 'Hesdinois'),
  ('62447', 'Hesdin-la-Forêt', 'Forestinois'),
  ('69024', 'Le Bois-d''Oingt', 'Buisantins'),
  ('69024', 'Val d''Oingt', 'Valdoniens · Valdoniennes'),
  ('72137', 'La Fresnaye-sur-Chédouet', 'Fresnayons'),
  ('72137', 'Villeneuve-en-Perseigne', 'Villeneuvois'),
  ('73227', 'Saint-Bon-Tarentaise', 'Saint-Bonais'),
  ('73227', 'Courchevel (commune)', 'Courchevellois'),
  ('73290', 'Val-Cenis', 'Valceniains'),
  ('73290', 'Termignon', 'Termignonais'),
  ('74112', 'Épagny (Haute-Savoie)', 'Épaniens'),
  ('74112', 'Epagny Metz-Tessy', 'Épatesserans · Épatesserannes'),
  ('74167', 'Marlens', 'Marlinois'),
  ('74167', 'Val de Chaise', 'Valchaisans'),
  ('74212', 'Le Petit-Bornand-les-Glières', 'Borniands'),
  ('74212', 'Glières-Val-de-Borne', 'Glièroises'),
  ('74275', 'Talloires', 'Talloiriens · Talloiriennes'),
  ('74275', 'Talloires-Montmin', 'Talloiro-Montminois'),
  ('76164', 'Caudebec-en-Caux', 'Caudebecquais'),
  ('76164', 'Rives-en-Seine', 'Seino-Riverains'),
  ('76476', 'Notre-Dame-de-Gravenchon', 'Gravenchonnais'),
  ('76476', 'Port-Jérôme-sur-Seine', 'Aubervillais'),
  ('77433', 'Saints (Seine-et-Marne)', 'Saintois · Saintoises'),
  ('77433', 'Beautheil-Saints', 'Beausaintois · Beausaintoises'),
  ('78158', 'Le Chesnay', 'Chesnaysiens'),
  ('78158', 'Le Chesnay-Rocquencourt', 'Chesnaycourtois'),
  ('79063', 'Cersay', 'Cersaisiens'),
  ('79063', 'Val en Vignes', 'Valenvignois'),
  ('79185', 'Mougon (Deux-Sèvres)', 'Mougonnais · Mougonnaises'),
  ('79185', 'Aigondigné', 'Aigondignois · Aigondignoises'),
  ('80155', 'Bussus-Bussuel', 'Bussuellois'),
  ('80155', 'Bussus-lès-Yaucourt', 'Bussussois · Bussussoises'),
  ('85008', 'Aubigny (Vendée)', 'Aubinois'),
  ('85008', 'Aubigny-Les Clouzeaux', 'Aubinois-Cluzéliens'),
  ('85009', 'Auzay', 'Auzaciens'),
  ('85009', 'Auchay-sur-Vendée', 'Auchayrois'),
  ('85019', 'Belleville-sur-Vie', 'Bellevillois'),
  ('85019', 'Bellevigny', 'Bellevignois'),
  ('85084', 'Les Essarts (Vendée)', 'Essartais'),
  ('85084', 'Essarts-en-Bocage', 'Essartois'),
  ('85090', 'La Flocellière', 'Flocéens'),
  ('85090', 'Sèvremont', 'Sèvremontains'),
  ('85146', 'Montaigu (Vendée)', 'Montacutains'),
  ('85146', 'Montaigu-Vendée', 'Montacutains · Montacutaines'),
  ('85152', 'La Mothe-Achard', 'Mothais'),
  ('85152', 'Les Achards', 'Achardais'),
  ('85154', 'Mouilleron-Saint-Germain', 'Mouilleronnais-Germinois'),
  ('85154', 'Mouilleron-en-Pareds', 'Mouilleronnais'),
  ('85194', 'Les Sables-d''Olonne (ancienne commune)', 'Sablais'),
  ('85194', 'Les Sables-d''Olonne', 'Sablais · Sablaises'),
  ('85197', 'Saint-André-Treize-Voies', 'Trévois'),
  ('85197', 'Montréverd', 'Montréverdois'),
  ('85213', 'Rives de l''Yon', 'Rivayonnais'),
  ('85213', 'Saint-Florent-des-Bois', 'Saint-Florentais'),
  ('85222', 'Saint-Gilles-Croix-de-Vie', 'Gillocruciens'),
  ('85222', 'Saint-Gilles-sur-Vie', 'Giras'),
  ('85289', 'La Tardière', 'Tardiérois'),
  ('85289', 'Terval', 'Tervalois'),
  ('86019', 'Beaumont (Vienne)', 'Beaumontois'),
  ('86019', 'Beaumont Saint-Cyr', 'Beaumontsaintcyriens'),
  ('86082', 'Couhé', 'Coéciens'),
  ('86082', 'Valence-en-Poitou', 'Picto-Valençois'),
  ('86115', 'Jaunay-Clan', 'Jaunay-Clanais'),
  ('86115', 'Jaunay-Marigny', 'Jaunay-Marins'),
  ('90068', 'Meroux', 'Méroutains'),
  ('90068', 'Meroux-Moval', 'Mervalois · Mervaloises'),
  ('91228', 'Évry', 'Évryens · Évryennes'),
  ('91228', 'Évry-Courcouronnes', 'Évry-Courcouronnais'),
  ('91390', 'Méréville (Essonne)', 'Mérévillois'),
  ('91390', 'Le Mérévillois', 'Mérévillois · Mérévilloises')
),
choisi as (
  select distinct on (v.code) v.code, v.gentile
    from candidats v
    join public.communes c on c.code = v.code
   order by v.code,
         (unaccent(lower(v.titre)) = unaccent(lower(c.nom))) desc,
         (unaccent(lower(v.titre)) like unaccent(lower(c.nom)) || ' (%') desc,
         (unaccent(lower(v.titre)) like '%' || unaccent(lower(c.nom)) || '%') desc,
         length(v.titre) desc
)
update public.communes c
   set gentile = choisi.gentile
  from choisi
 where choisi.code = c.code
   and c.gentile is distinct from choisi.gentile;

-- ---------------------------------------------------------------------
--  Controle
-- ---------------------------------------------------------------------
select nom, departement, gentile
  from public.communes
 where code in ('01215', '01033', '09334', '08105')
 order by nom;
-- =====================================================================
